version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}         
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}     
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db    
  app:
    container_name: node_backend
    image: node20                                      
    env_file: .env
    ports:
      - "3000:3000" 
    environment:
      - DB_HOST=mongodb_container
      - DB_USER=${MONGODB_USER}                           
      - DB_PASSWORD=${MONGODB_PASSWORD}                  
      - DB_NAME=${MONGODB_DATABASE}                       
      - DB_PORT=27017                                    
    depends_on:
      - mongodb_container                                 
volumes:
  mongodb_data_container:
